### ISSUE TITLE
[USER STORY] Character Selection Feature

### ISSUE THREAD

**Issue by UsmanButt1** [UsmanButt1/script-spartans#1]
As *a user* I want *to see a selection of characters* so that *I can choose the character I want to play as*

# Tasks:
- [x] Insert HTML character code
- [x] Add CSS styling to character selection area
- [x] Link JavaScript coding to enable user interactivity
- [x] Make the selection responsive
- [x] Test responsiveness
