### ISSUE TITLE
[USER STORY] Basic HTML and CSS Code Structure

### ISSUE THREAD

**Issue by UsmanButt1** [UsmanButt1/script-spartans#3]
As *a site owner* I want *to have the basic HTML and CSS structure in place* so that *I can include additional functionality and features later*

# Tasks:
- [x] Insert HTML boilerplate and wireframe-specific code
- [x] Add CSS styling to entire webpage
- [x] Link Bootstrap and JavaScript to the HTML webpage
- [x] Make the selection responsive
- [x] Test responsiveness
