### ISSUE TITLE
[USER STORY] Create Wireframes for Website

### ISSUE THREAD

**Issue by UsmanButt1** [UsmanButt1/script-spartans#4]
As *a site owner* I want *to see a basic design for the final webpage* so that *I can have better focus on coding and seeing the wireframe come to fruition*

# Tasks:
- [x] Create basic structure of design for desktop of main webpage
- [x] Add colour scheme to the various elements of the webpage
- [x] Create the above two to tablet and phone views
